# Generated by Django 3.0.7 on 2020-06-29 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_thing_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform_to_bought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='thing',
            name='bought_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='things.Platform_to_bought'),
        ),
    ]
